#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i --write-sub " \
	ytp="yt -o \"%(playlist_index)s-%(title)s.%(ext)s\"" \
	yta="yt-dlp -x -f bestaudio/best --audio-format mp3" \
	ytpa="yta -o \"%(playlist_index)s-%(title)s.%(ext)s\"" \
	ffmpeg="ffmpeg -hide_banner" \
    mpv="mpv --save-position-on-quit"

# Colorize commands when possible.
alias \
	ls="exa -h --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \


# Emacs
alias emacsc="emacsclient -c -a 'emacs'"
alias emacsd="killall emacs; emacs --daemon"
