#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#xcompmgr &		# xcompmgr for transparency
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'loginctl suspend' '' & # xidlehook to suspend automatically after 30 minutes of idle (for runit)
#xidlehook --not-when-audio --not-when-fullscreen --timer 1800 '$systemctl suspend' '' & # for systemd
autostart="pipewire mpd picom dunst unclutter sxhkd fcitx"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
